version: "3.9"

services:
  web:
    image: cloud_td1
    ports:
      - "3000:3000/tcp"
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1
      - POSTGRES_HOST=database
    depends_on:
      - database
    entrypoint: "bash -c '/app/wait-for-it.sh $${POSTGRES_HOST}:5432 -- node server.js'"

  
  database:
      image: postgres:14
      environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1
