version: "3.9"

services:
  web:
    image: cloud_td1
    ports:
      - "3000:3000/tcp"
#    depends_on:
#      - postgres
  
#  database:
    #    image: postgres:14
      #environment:
      #- POSTGRES_PASSWORD=dev_password
      #- POSTGRES_USER=si5_sacc
      #- POSTGRES_DB=td_1
